### ISSUE TITLE
Unusial error syntax convertion. Comma at the end of the object.

### ISSUE THREAD

**Issue by av125375** [hjson/hjson#94]
In the input i have next description:

  {
    test: 1
  },

Comma at the end.
I am think this no matter, but this is lead to the syntax error.
It is bug or necessary thing?

**Comment by trobro** [comment]
It should not lead to a syntax error. The Hjson specification allows trailing commas:

https://hjson.github.io/syntax.html

Which Hjson-implementation did you find the problem in? It would be better to create an issue in the specific implementation repository.

**Comment by InterfaceBoy** [comment]
index.js:194 Error: Found ',' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 1,153 >>>!DOCTYPE html><html  ...
    at h (hjson-parse.js:41)
    at y (hjson-parse.js:163)
    at C (hjson-parse.js:353)
    at T (hjson-parse.js:434)
    at Object.t.exports [as parse] (hjson-parse.js:454)
    at index.js:186
    at l (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:6)

**Comment by trobro** [comment]
> It should not lead to a syntax error.

Correction: It is a syntax error if an Hjson file contains only this:

```
{
test: 1
},
```

A comma is not allowed after the root object. Commas are only allowed after elements (either in objects or in arrays), but the root object is not an element of anything else. The syntax here below would however be allowed, because then the comma is placed after an element and not after the (braceless) root object:

```
key: {
test: 1
},
```
